name: Upload Data to Staging

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  upload:
    uses: unitysvc-labs/.github/.github/workflows/seller-upload-staging.yml@main
    secrets: inherit
    permissions:
      contents: write
