name: Validate Data

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "specs/**"
      - ".github/workflows/validate-data.yml"
  push:
    branches: [main]
    paths:
      - "specs/**"
      - ".github/workflows/validate-data.yml"

jobs:
  validate-data:
    uses: unitysvc-labs/.github/.github/workflows/seller-validate-data.yml@main
